# Assignment 5
Sanna Sharma 
1024170094

In [2]:
# Question 1
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Original Array:", arr)

print("After adding 2:", arr + 2)
print("After multiplying by 3:", arr * 3)
print("After dividing by 2:", arr / 2)

Original Array: [10 20 30 40 50]
After adding 2: [12 22 32 42 52]
After multiplying by 3: [ 30  60  90 120 150]
After dividing by 2: [ 5. 10. 15. 20. 25.]


In [ ]:
# Question 2
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])

print("Original Array:", arr)
print("Reversed Array:", arr[::-1])

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(x == most_frequent)[0]

print()

print("Most frequent value:", most_frequent)
print("Indices:", indices)

print()

y = np.array([1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(y == most_frequent)[0]

print("Most frequent value:", most_frequent)
print("Indices:", indices)

Original Array: [1 2 3 6 4 5]
Reversed Array: [5 4 6 3 2 1]

Most frequent value: 1
Indices: [0 5 7 8 9]

Most frequent value: 3
Indices: [3 7 8]


In [6]:
# Question 3
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# a) Access 1st row, 2nd column
print("1st row, 2nd column:", arr[0, 1])

# b) Access 3rd row, 1st column
print("3rd row, 1st column:", arr[2, 0])

1st row, 2nd column: 20
3rd row, 1st column: 70


In [1]:
# Question 4
import numpy as np

Sanna_Sharma = np.linspace(10, 100, 25)

print("Array:")
print(Sanna_Sharma)

print("Dimensions:", Sanna_Sharma.ndim)
print("Shape:", Sanna_Sharma.shape)
print("Total elements:", Sanna_Sharma.size)
print("Data type:", Sanna_Sharma.dtype)
print("Total bytes:", Sanna_Sharma.nbytes)

# Transpose using reshape
transposed = Sanna_Sharma.reshape(1, 25)

print("Transpose using reshape:")
print(transposed)

# Transpose using T
print("Transpose using T:")
print(Sanna_Sharma.T)

Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape:
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
Transpose using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [2]:
# Question 5
import numpy as np

# Create 2-D array
ucs420_Sanna_Sharma = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original Array:")
print(ucs420_Sanna_Sharma)
print()

# Mean
print("Mean:", np.mean(ucs420_Sanna_Sharma))

# Median
print("Median:", np.median(ucs420_Sanna_Sharma))

# Maximum
print("Maximum:", np.max(ucs420_Sanna_Sharma))

# Minimum
print("Minimum:", np.min(ucs420_Sanna_Sharma))

# Unique elements
print("Unique elements:", np.unique(ucs420_Sanna_Sharma))

# Reshape to 4 rows and 3 columns
ucs420_Sanna_Sharma = ucs420_Sanna_Sharma.reshape(4, 3)

print("\nAfter Reshaping to 4 x 3:")
print(ucs420_Sanna_Sharma)

# Resize to 2 rows and 3 columns
resized_ucs420_Sanna_Sharma = np.resize(ucs420_Sanna_Sharma, (2, 3))

print("\nAfter Resizing to 2 x 3:")
print(resized_ucs420_Sanna_Sharma)

Original Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

After Reshaping to 4 x 3:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

After Resizing to 2 x 3:
[[10 20 30]
 [40 50 60]]
